apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ingress-gateway-configuration
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"   # Domain name of the external website
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: topitop-gateway-configuration
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"   # Domain name of the external website
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
    name: client-cluster-ip-service
    namespace: default
spec:
    gateways:
        - ingress-gateway-configuration
    hosts:
        - "*"
    http:
        - match:
              - uri:
                    prefix: /api/
          rewrite:
            uri: "/"
          route:
              - destination:
                    host: server-cluster-ip-service
        - match:
              - uri:
                    prefix: /
          route:
              - destination:
                    host: client-cluster-ip-service
                    subset: original
                weight: 90
              - destination:
                    host: client-cluster-ip-service
                    subset: experimental
                weight: 10
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
    name: client-cluster-ip-service
    namespace: default
spec:
    host: client-cluster-ip-service
    subsets:
        -
            labels:
                version: original
            name: original
        -
            labels:
                version: experimental
            name: experimental
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
    name: server-cluster-ip-service
    namespace: default
spec:
    host: server-cluster-ip-service

