istioctl kube-inject -f client-deployment.yaml | kubectl apply -f -
istioctl kube-inject -f server-deployment.yaml | kubectl apply -f -
istioctl kube-inject -f worker-deployment.yaml | kubectl apply -f -
istioctl kube-inject -f redis-deployment.yaml | kubectl apply -f -
istioctl kube-inject -f postgres-deployment.yaml | kubectl apply -f -
istioctl kube-inject -f client-cluster-ip-service.yaml | kubectl apply -f -
istioctl kube-inject -f server-cluster-ip-service.yaml | kubectl apply -f -
istioctl kube-inject -f postgres-cluster-ip-service.yaml | kubectl apply -f -
istioctl kube-inject -f redis-cluster-ip-service.yaml | kubectl apply -f -
